# Generated by Django 2.0.13 on 2022-11-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfun', '0002_auto_20221113_2308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankcarddetails',
            table='bankcarddetails',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Bank.project.employee',
        ),
    ]
