# Generated by Django 2.0.13 on 2022-11-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfun', '0003_auto_20221113_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
